#!/bin/bash
# Build this keymap WITH the FocusGuard device key and flash it, leaving no copy of the key
# on disk.
#
# The key is read from the login Keychain (macOS asks you to allow it: only FocusGuard
# reads it silently) into a header in a private temporary directory. The whole build goes
# there too, and everything is deleted when the script exits, flashed or not. The repo never holds the
# key, so publishing or sharing the clone exposes nothing.
#
#   tools/fg-flash.sh     build, then flash with nu-isp-cli once the keyboard is in ISP mode
#
# Without a key, `qmk compile -kb ducky/one2sf/1967st/ansi -km illixion` still builds a
# working firmware with the secure relay compiled out.
set -euo pipefail
umask 077

SERVICE="com.illixion.focusguard.keyboard"
ACCOUNT="${FG_KEYBOARD_ACCOUNT:-ducky-one2sf-1967st}"
KB="ducky/one2sf/1967st/ansi"
KM="illixion"
TARGET="ducky_one2sf_1967st_ansi_illixion"

HERE="$(cd "$(dirname "$0")/.." && pwd)"
QMK_ROOT="$(git -C "$HERE" rev-parse --show-toplevel)"
command -v qmk >/dev/null || { echo "qmk CLI not found" >&2; exit 1; }
command -v nu-isp-cli >/dev/null || { echo "nu-isp-cli not found (cargo install nu-isp-cli)" >&2; exit 1; }
command -v arm-none-eabi-objcopy >/dev/null || { echo "arm-none-eabi-objcopy not found (part of the QMK toolchain)" >&2; exit 1; }
if [ -e "$HERE/fg/fg_secret.h" ]; then
    echo "fg/fg_secret.h exists: it is an on-disk copy of an old key. Delete it (and rotate: tools/fg-provision.sh --rotate)." >&2
    exit 1
fi

# $TMPDIR is per-user and private on macOS; mktemp makes the directory 0700 on top.
WORK="$(mktemp -d "${TMPDIR:-/tmp}/fg-flash.XXXXXXXX")"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT
trap 'exit 130' INT TERM
mkdir "$WORK/key" "$WORK/build"

echo "Reading the device key from the Keychain (approve the prompt)…"
if ! key="$(security find-generic-password -s "$SERVICE" -a "$ACCOUNT" -w 2>/dev/null)"; then
    echo "FAIL: no key in the Keychain ($SERVICE / $ACCOUNT), or access was denied. Run tools/fg-provision.sh first." >&2
    exit 1
fi
if ! [[ "$key" =~ ^[0-9a-f]{64}$ ]]; then
    unset key
    echo "FAIL: the Keychain item is not a 64-digit hex key." >&2
    exit 1
fi
{
    echo "// Generated by tools/fg-flash.sh for one build; deleted when the build ends."
    printf '#define FG_SECRET_KEY_BYTES {'
    for i in $(seq 0 31); do printf '0x%s,' "${key:$((i * 2)):2}"; done
    echo '}'
} > "$WORK/key/fg_device_key.h"
unset key

echo "Building…"
# Only the .elf is asked for, inside $WORK: QMK's `.bin` rules (the default build, `-t bin`
# and the generic %.bin rule) all copy the image into the repo root, which would leave the
# key there. BUILD_DIR must be given to make itself; paths.mk sets it with :=.
ELF="$WORK/build/$TARGET.elf"
BIN="$WORK/build/$TARGET.bin"
(cd "$QMK_ROOT" && BUILD_DIR="$WORK/build" qmk compile -kb "$KB" -km "$KM" -t "$ELF" \
    -e FG_KEY_DIR="$WORK/key" -e BUILD_DIR="$WORK/build") >"$WORK/build.log" 2>&1 || {
    grep -E "error|Error" "$WORK/build.log" | head -20 >&2
    echo "FAIL: build failed." >&2
    exit 1
}
rm -f "$WORK/key/fg_device_key.h"
[ -f "$ELF" ] || { echo "FAIL: build produced no $TARGET.elf" >&2; exit 1; }
arm-none-eabi-objcopy -O binary "$ELF" "$BIN"      # what QMK's BIN step runs, minus the copy
echo "Built $(wc -c < "$BIN" | tr -d ' ') bytes with the key."

echo
echo "Put the keyboard in ISP mode: unplug it, hold D+L, plug it back in."
read -r -p "Press Return when it is ready (Ctrl-C to cancel)… " _
nu-isp-cli flash "$BIN"
echo "OK: flashed. The build directory with the key has been deleted."
